### ISSUE TITLE
Test suite failures are not reported

### ISSUE THREAD

**Issue by ohana54** [itereshchenkov/jest-teamcity#12]
Hi,
We switched to this library from `jest-teamcity-reporter`, and noticed that general test suite failures are not being reported.
The other library indeed reports them as a "fake" test: https://github.com/winterbe/jest-teamcity-reporter/blob/2ebc892673611123abe34328a97a37900e277092/index.js#L25

I believe something similar should be done here.
I won't have time this week to submit a PR, so I'm opening this issue in case someone else wants to take it.
Thanks!

**Comment by itereshchenkov** [comment]
I assume this issue was addressed withing this PR #16. Version 1.9.0 was published with the mentioned update. Please feel free to update you deps and let me know if it fits your needs

**Comment by ohana54** [comment]
Thanks, checking it now.

**Comment by ohana54** [comment]
Looks good, and it's a funny coincidence that my co-worker opened the PR 👍 
Thanks @yurynix!!
