### ISSUE TITLE
jest --coverage support

### ISSUE THREAD

**Issue by isakb** [itereshchenkov/jest-teamcity#3]
It would be nice to output coverage data to team city as well.

(See https://github.com/winterbe/jest-teamcity-reporter/issues/14#issuecomment-313716217.)

**Comment by itereshchenkov** [comment]
@isakb Thanks a lot for your suggestion. I will check it and if it's possible, I'll add this feature with the next release.

**Comment by isakb** [comment]
@itereshchenkov note the last comments on https://github.com/winterbe/jest-teamcity-reporter/issues/14 - maybe not necessary to add anyway?

**Comment by itereshchenkov** [comment]
Yes, I saw this comment already.
I checked and it works really good with the **teamcity** as **coverageReporters**

Example:
```
"coverageReporters": [
     "teamcity", "lcov"
],
```

**Comment by itereshchenkov** [comment]
I'm closing the issue since there is nothing to do.

**Comment by an83** [comment]
See my comment on https://github.com/winterbe/jest-teamcity-reporter/issues/14#issuecomment-364281857
