### ISSUE TITLE
Access to jest-teamcity results?

### ISSUE THREAD

**Issue by HairyMaclary** [itereshchenkov/jest-teamcity#4]
Hi,

TeamCity allows me to download the jest-teamcity test results (test duration, etc) as a CSV file. Is there a way to access this information in a build step, or at least convert it to an artifact?

I'd like to automatically collect results across builds and make some comparisons. 

Thank you...

**Comment by itereshchenkov** [comment]
Hey,

Have you tried to configure the artifacts storage?
See [Configuring+Artifacts+Storage](https://confluence.jetbrains.com/display/TCD10/Configuring+Artifacts+Storage)

Also you can use some external storage for it

**Comment by HairyMaclary** [comment]
Thanks for the speedy reply Ivan. I'm wondering if the csv file is not actually an artifact. Could it be that TC generates the csv file from the buildlog (which actually is a hidden artifact) as required?
